name: Build python deps on linux
on:
  push:
    branches: 
      - feature/ga-python-builds

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.wheel_combinations.platform }}
    runs-on: ${{ matrix.wheel_combinations.arch }}
    strategy:
      matrix:
        python_versions: [
          ["3.7","cp37-*"],
          ["3.8","cp38-*"],
          ["3.9","cp39-*"],
          ["3.10","cp310-*"],
          ["3.11","cp311-*"],
          ["3.12","cp312-*"],
        ]
        wheel_combinations: [
          {platform:"ubuntu-latest",arch:"x86_64"},
          {platform:"windows-latest",arch:"x86_64"},
          {platform:"macos13",arch:"x86_64"},
          {platform:"macos13",arch:"arm64"},
          {platform:"macos14",arch:"x86_64"},
          {platform:"macos14",arch:"arm64"},

        ]
      fail-fast: false

    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python_version: ${{ matrix.python_versions[0] }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.0

      - name: Download and Untar File - Windows
        if: matrix.wheel_combinations.platform == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://files.pythonhosted.org/packages/0c/2a/23943e19b4bbbdad60a9d881e44cd53bb48b31c7419ebb7b983edfbbb708/grpcio-1.63.0.tar.gz" -OutFile "grpcio-1.63.0.tar.gz"
          Expand-Archive -Path "grpcio-1.63.0.tar.gz" -DestinationPath "grpcio-1.63.0"
          cd grpcio-1.63.0

      - name: Download and Untar File - Unix
        if: matrix.wheel_combinations.platform != 'windows-latest'
        run: |
          cd /tmp
          wget -O grpcio-1.63.0.tar.gz https://files.pythonhosted.org/packages/0c/2a/23943e19b4bbbdad60a9d881e44cd53bb48b31c7419ebb7b983edfbbb708/grpcio-1.63.0.tar.gz
          tar xzf grpcio-1.63.0.tar.gz
          echo $PWD
          ls

      - name: Build wheels
        run: |
          cd /tmp
          echo $PWD
          ls
          cd /tmp/grpcio-1.63.0/
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS: ${{ matrix.wheel_combinations.arch }}
          CIBW_BUILD: ${{ matrix.python_versions[1] }}


      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.wheel_combinations.platform }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          
