name: Build python deps on linux
on:
  push:
    branches: 
      - feature/ga-python-builds

jobs:
  build_wheels:
    name: ${{ matrix.libraries[1] }}-${{ matrix.wheel_combinations[0] }}-${{ matrix.wheel_combinations[1] }}-py${{ matrix.python_versions[0] }}
    runs-on: ${{ matrix.wheel_combinations[0] }}
    strategy:
      matrix:
        libraries: [

          #["https://files.pythonhosted.org/packages/78/63/66c03eb51f0d241862083deb3f17ab5fce08cf6b347db7887bcb4d1a194e/cryptography-42.0.7.tar.gz", "cryptography-42.0.7.tar.gz"],
          #["https://files.pythonhosted.org/packages/6b/b0/e595ce2a2527e169c3bcd6c33d2473c1918e0b7f6826a043ca1245dd4e5b/crcmod-1.7.tar.gz", "crcmod-1.7.tar.gz"],
          #["https://files.pythonhosted.org/packages/90/c7/6dc0a455d111f68ee43f27793971cf03fe29b6ef972042549db29eec39a2/psutil-5.9.8.tar.gz", "psutil-5.9.8.tar.gz"],
          #["https://files.pythonhosted.org/packages/0c/2a/23943e19b4bbbdad60a9d881e44cd53bb48b31c7419ebb7b983edfbbb708/grpcio-1.63.0.tar.gz", "grpcio-1.63.0.tar.gz"],  
          ["https://files.pythonhosted.org/packages/5e/d8/65adb47d921ce828ba319d6587aa8758da022de509c3862a70177a958844/protobuf-4.25.3.tar.gz", "protobuf-4.25.3.tar.gz"],


           #  ["https://files.pythonhosted.org/packages/87/5b/aae44c6655f3801e81aa3eef09dbbf012431987ba564d7231722f68df02d/MarkupSafe-2.1.5.tar.gz", "MarkupSafe-2.1.5.tar.gz"],
          #  ["https://files.pythonhosted.org/packages/ca/e9/0b36987abbcd8c9210c7b86673d88ff0a481b4610630710fb80ba5661356/bcrypt-4.1.3.tar.gz", "bcrypt-4.1.3.tar.gz"],
          #  ["https://files.pythonhosted.org/packages/2c/f0/f02e2d150d581a294efded4020094a371bbab42423fe78625ac18854d89b/lazy-object-proxy-1.10.0.tar.gz", "lazy-object-proxy-1.10.0.tar.gz"],
          #  ["https://files.pythonhosted.org/packages/f9/7e/a424029f350aa8078b75fd0d360a787a273ca753a678d1104c5fa4f3072a/typed_ast-1.5.5.tar.gz", "typed_ast-1.5.5.tar.gz"],

          
          
          # ["https://files.pythonhosted.org/packages/86/15/8473774dfdd0fa901cfb1ad0d590c5a3e6a7c5906dc23b47619ccfc7fe62/grpcio_tools-1.63.0.tar.gz", "grpcio_tools-1.63.0.tar.gz"],
          
          # ["https://files.pythonhosted.org/packages/68/ce/95b0bae7968c65473e1298efb042e10cafc7bafc14d9e4f154008241c91d/cffi-1.16.0.tar.gz", "cffi-1.16.0.tar.gz"],
          # ["https://files.pythonhosted.org/packages/a7/22/27582568be639dfe22ddb3902225f91f2f17ceff88ce80e4db396c8986da/PyNaCl-1.5.0.tar.gz", "PyNaCl-1.5.0.tar.gz"],
          # ["https://files.pythonhosted.org/packages/95/4c/063a912e20bcef7124e0df97282a8af3ff3e4b603ce84c481d6d7346be0a/wrapt-1.16.0.tar.gz", "wrapt-1.16.0.tar.gz"],
          # ["https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz", "PyYAML-6.0.1.tar.gz"],

        #  ["https://files.pythonhosted.org/packages/87/5b/aae44c6655f3801e81aa3eef09dbbf012431987ba564d7231722f68df02d/MarkupSafe-2.1.5.tar.gz", "MarkupSafe-2.1.5.tar.gz"],
        #  ["https://files.pythonhosted.org/packages/ca/e9/0b36987abbcd8c9210c7b86673d88ff0a481b4610630710fb80ba5661356/bcrypt-4.1.3.tar.gz", "bcrypt-4.1.3.tar.gz"],
        #  ["https://files.pythonhosted.org/packages/2c/f0/f02e2d150d581a294efded4020094a371bbab42423fe78625ac18854d89b/lazy-object-proxy-1.10.0.tar.gz", "lazy-object-proxy-1.10.0.tar.gz"],
        #  ["https://files.pythonhosted.org/packages/f9/7e/a424029f350aa8078b75fd0d360a787a273ca753a678d1104c5fa4f3072a/typed_ast-1.5.5.tar.gz", "typed_ast-1.5.5.tar.gz"],
        ]
        python_versions: [
          #["3.7","cp37-*"],
          ["3.8","cp38-*"],
          ["3.9","cp39-*"],
          ["3.10","cp310-*"],
          ["3.11","cp311-*"],
          ["3.12","cp312-*"],
        ]
        wheel_combinations: [
          ["ubuntu-latest", "x86_64"],
          ["windows-latest", "AMD64"],
          #["macos13", "x86_64"],
     #     ["macos14", "x86_64"],
        ]
      fail-fast: false

    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python_version: ${{ matrix.python_versions[0] }}

      - name: Install python deps
        run: python -m pip install cibuildwheel==2.17.0

      - name: Download and Untar File - Windows
        if: matrix.wheel_combinations[0] == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri ${{ matrix.libraries[0] }} -OutFile ${{ matrix.libraries[1] }}

      - name: Download and Untar File - Unix
        if: matrix.wheel_combinations[0] != 'windows-latest'
        run: |
          wget -O ${{ matrix.libraries[1] }} ${{ matrix.libraries[0] }}

      - name: Build wheels
        run: |
          python -m cibuildwheel ${{ matrix.libraries[1] }} --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS: ${{ matrix.wheel_combinations[1] }}
          CIBW_BUILD: ${{ matrix.python_versions[1] }}
          CIBW_SKIP: '*-musllinux_*'


      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.libraries[1] }}-${{ matrix.wheel_combinations[0] }}-${{ matrix.wheel_combinations[1] }}-py${{ matrix.python_versions[0] }}
          path: ./wheelhouse/*.whl
          
