name: Build python deps on linux
on:
  push:
    branches: 
      - feature/ga-python-builds

jobs:
  build_wheel:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Pull source package from PyPI
        run: |
          wget https://files.pythonhosted.org/packages/0c/2a/23943e19b4bbbdad60a9d881e44cd53bb48b31c7419ebb7b983edfbbb708/grpcio-1.63.0.tar.gz
          tar xvf grpcio-1.63.0.tar.gz
      - name: Build wheel and upload to GCS
        id: build_wheel
        run: |
          cd grpcio-1.63.0
          #python -m pip install --user --upgrade build
          #python -m build
          mkdir dist
          echo -n "NOTHING TO SEE HERE" > dist/artifact.whl
          WHEEL_FILE=$(find ./dist/*.whl)
          echo "WHEEL_FILE=${WHEEL_FILE}" >> GITHUB_OUTPUT
          echo $WHEEL_FILE 

      - uses: actions/upload-artifact@v4
        with:
          name: "python 3.7 grpcio 1.63 ubuntu"
          path: ${{ steps.build_wheel.outputs.WHEEL_FILE }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: false
          
